### ISSUE TITLE
Crash on FileUtils.isOk()

### ISSUE THREAD

**Issue by veniosg** [veniosg/Dir#34]
```
java.lang.NullPointerException: 
  at com.veniosg.dir.util.FileUtils.isOk(FileUtils.java:255)
  at com.veniosg.dir.view.widget.PathView.cd(PathView.java:209)
  at com.veniosg.dir.view.widget.PathView.cd(PathView.java:202)
  at com.veniosg.dir.fragment.SimpleFileListFragment.onEmptyViewClicked(SimpleFileListFragment.java:739)
  at com.veniosg.dir.fragment.FileListFragment$3.onClick(FileListFragment.java:123)
  at android.view.View.performClick(View.java:5612)
  at android.view.View$PerformClick.run(View.java:22288)
  at android.os.Handler.handleCallback(Handler.java:751)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6123)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

```

**Comment by veniosg** [comment]
Why is it even getting nulls?
