### ISSUE TITLE
Crash on DetailsDialog.onCreateDialog()

### ISSUE THREAD

**Issue by veniosg** [veniosg/Dir#36]
```
java.lang.NullPointerException: 
  at com.veniosg.dir.dialog.DetailsDialog.onCreateDialog(DetailsDialog.java:78)
  at android.support.v4.app.DialogFragment.getLayoutInflater(DialogFragment.java:308)
  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1078)
  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1259)
  at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
  at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1624)
  at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
  at android.os.Handler.handleCallback(Handler.java:815)
  at android.os.Handler.dispatchMessage(Handler.java:104)
  at android.os.Looper.loop(Looper.java:207)
  at android.app.ActivityThread.main(ActivityThread.java:5765)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

```

**Comment by veniosg** [comment]
Crazy log, also seems to have stopped occuring. Closing.
